### ISSUE TITLE
(if necessary) Setup new Ubuntu distribution in infrastructure

### ISSUE THREAD

**Issue by clalancette** [ros2/release-tracking#16]

**Comment by clalancette** [comment]
This is only required in even years, i.e. when a new Ubuntu LTS is about to be released.  The below list is very approximate; work with OSRF Infrastructure team to enable this platform.

* Setup new apt repos
* Update CI infrastructure to support new platforms.  Example from Foxy:
  * [add Focal option ci#376](https://github.com/ros2/ci/pull/376) and 
  * [Default to Ubuntu Focal for Linux jobs ci#414](https://github.com/ros2/ci/pull/414)
* Create Rolling Docker images for the new platforms in [REP-2000](https://www.ros.org/reps/rep-2000.html) for all targets:
  * [Update ROS Rolling to Jammy osrf/docker_images#601](https://github.com/osrf/docker_images/pull/601)
* Add newly supported platforms to list of platforms for each Python package (in stdeb.cfg). Use [ros_release_python](https://github.com/ros-infrastructure/ros_release_python). Goal is to make the currently released versions available in the new distros using the --include option.  In order of dependency:
  * colcon
  * catkin_pkg - Example from Foxy: [Add a Suite3 option with Ubuntu Focal. ros-infrastructure/catkin_pkg#271](https://github.com/ros-infrastructure/catkin_pkg/pull/271)
  * rospkg - Example from Foxy: [add Suite3 including Focal ros-infrastructure/rospkg#184](https://github.com/ros-infrastructure/rospkg/pull/184)
  * rosdistro - Example from Foxy: [add Suite3 including Focal ros-infrastructure/rosdistro#148](https://github.com/ros-infrastructure/rosdistro/pull/148)
  * rosdep - Example from Foxy: [Add Suite3 option with Ubuntu Focal ros-infrastructure/rosdep#734](https://github.com/ros-infrastructure/rosdep/pull/734)
  * bloom - Example from Foxy: [Add Suite3 option with Ubuntu Focal ros-infrastructure/bloom#558](https://github.com/ros-infrastructure/bloom/pull/558)
  * rosinstall_generator - Example from Foxy: [Add Suite3 option with Ubuntu Focal ros-infrastructure/rosinstall_generator#62](https://github.com/ros-infrastructure/rosinstall_generator/pull/62)
  * vcstool - Example from Foxy: [add Suite3 including Focal dirk-thomas/vcstool#112](https://github.com/dirk-thomas/vcstool/pull/112)

**Comment by nuclearsandwich** [comment]
Tracker for 24.04 https://github.com/ros2/ros2/issues/1511
