### ISSUE TITLE
Update vendor packages

### ISSUE THREAD

**Issue by clalancette** [ros2/release-tracking#23]

**Comment by clalancette** [comment]
Upgrade the vendor packages to match what is in the Ubuntu distribution currently being used.  For instance, Humble was on Ubuntu 22.04, so make the vendor packages match whatever versions are packaged in Ubuntu 22.04.

Basically update these repos:
https://github.com/search?q=org%3Aros2+vendor&type=repositories

> Note: When doing these bumps also run CI for windows debug.

**Comment by marcoag** [comment]
List of vendor repos and whoever is working on upgrade:

- [x] [ros2/libyaml_vendor](https://github.com/ros2/libyaml_vendor) @marcoag 
- [x] [ros2/mimick_vendor](https://github.com/ros2/mimick_vendor)  This one is...weird.  Upstream is mostly dead, but we have our own forked version that we then vendor.  So we are up-to-date here by definition.
- [x] [ros2/yaml_cpp_vendor](https://github.com/ros2/yaml_cpp_vendor) @marcoag https://github.com/ros2/yaml_cpp_vendor/pull/48
- [x] [ros2/tinyxml2_vendor](https://github.com/ros2/tinyxml2_vendor) @marcoag same as tinyxml?
- [x] [ros2/spdlog_vendor](https://github.com/ros2/spdlog_vendor) @marcoag https://github.com/ros2/spdlog_vendor/pull/35
- [x] [ros2/pybind11_vendor](https://github.com/ros2/pybind11_vendor) @clalancette https://github.com/ros2/pybind11_vendor/pull/28
- [x] [ros2/console_bridge_vendor](https://github.com/ros2/console_bridge_vendor) @clalancette 
- [x] [ros2/orocos_kdl_vendor](https://github.com/ros2/orocos_kdl_vendor) @clalancette 
- [x] [ament/google_benchmark_vendor](https://github.com/ament/google_benchmark_vendor) @marcoag https://github.com/ament/google_benchmark_vendor/pull/29
- [x] [ament/googletest](https://github.com/ament/googletest) @clalancette 
- [x] [ament/uncrustify_vendor](https://github.com/ament/uncrustify_vendor) @clalancette https://github.com/ament/uncrustify_vendor/pull/37
- [x] [gazebo-release/gz_cmake_vendor](https://github.com/gazebo-release/gz_cmake_vendor)
- [x] [gazebo-release/gz_math_vendor](https://github.com/gazebo-release/gz_math_vendor)
- [x] [gazebo-release/gz_utils_vendor](https://github.com/gazebo-release/gz_utils_vendor)

Ones we can skip:

~~- [ ] [ros2/tinyxml_vendor](https://github.com/ros2/tinyxml_vendor)~~
~~- [ ] [ros2/darknet_vendor](https://github.com/ros2/darknet_vendor)~~
~~- [ ] [ros2/poco_vendor](https://github.com/ros2/poco_vendor)~~
~~- [ ] [ros2/tinydir_vendor](https://github.com/ros2/tinydir_vendor)~~
~~- [ ] [ros2/ifcfg_vendor](https://github.com/ros2/ifcfg_vendor)~~

**Comment by clalancette** [comment]
> List of vendor repos and whoever is working on upgrade:
> 
>     * [ ]  [ros2/tinyxml_vendor](https://github.com/ros2/tinyxml_vendor) @marcoag Not needed?

Correct, we no longer depend on this one.  We can skip it.

> 
>     * [ ]  [ros2/libyaml_vendor](https://github.com/ros2/libyaml_vendor) @marcoag
> 
>     * [ ]  [ros2/darknet_vendor](https://github.com/ros2/darknet_vendor)

We can skip this one; it is not in the core.

>     * [ ]  [ros2/mimick_vendor](https://github.com/ros2/mimick_vendor)
> 
>     * [ ]  [ros2/yaml_cpp_vendor](https://github.com/ros2/yaml_cpp_vendor) @marcoag [Upgrade to yaml-cpp 0.8.0 yaml_cpp_vendor#48](https://github.com/ros2/yaml_cpp_vendor/pull/48)
> 
>     * [ ]  [ros2/tinyxml2_vendor](https://github.com/ros2/tinyxml2_vendor) @marcoag same as tinyxml?
> 
>     * [ ]  [ros2/spdlog_vendor](https://github.com/ros2/spdlog_vendor) @marcoag [Upgrade to v1.12.0. spdlog_vendor#35](https://github.com/ros2/spdlog_vendor/pull/35)
> 
>     * [ ]  [ros2/pybind11_vendor](https://github.com/ros2/pybind11_vendor)
> 
>     * [ ]  [ros2/poco_vendor](https://github.com/ros2/poco_vendor)

We can skip this one; the core doesn't depend on it anymore.

>     * [ ]  [ros2/console_bridge_vendor](https://github.com/ros2/console_bridge_vendor)
> 
>     * [ ]  [ros2/tinydir_vendor](https://github.com/ros2/tinydir_vendor)

We can skip this one; the core doesn't depend on it anymore.

>     * [ ]  [ros2/orocos_kdl_vendor](https://github.com/ros2/orocos_kdl_vendor)
> 
>     * [ ]  [ros2/ifcfg_vendor](https://github.com/ros2/ifcfg_vendor)

We can skip this one; the core doesn't depend on it anymore.

I'm going to go through the previous comment and strike-out the ones that we don't need to do.

**Comment by ahcorde** [comment]
can we consider this as done ? @marcoag and @clalancette  ?

**Comment by clalancette** [comment]
Yes!  Good call.
