### ISSUE TITLE
Release!

### ISSUE THREAD

**Issue by clalancette** [ros2/release-tracking#36]

**Comment by clalancette** [comment]
1. Add known issues to equivalent of https://docs.ros.org/en/humble/Releases/Release-Humble-Hawksbill.html
2. Last minute smoke testing on all platforms
3. Edit front page of https://docs.ros.org/ to point to new release.
4. Merge documentation PR to mark distribution active. Also add pages for next turtle release but do not commit actual name until right before release like: https://github.com/ros2/ros2_documentation/pull/3610
5. Merge documentation PR to move back from 'testing' repository to main repository, like: https://github.com/ros2/ros2_documentation/pull/2580
6. Deploy the documentation by running https://build.ros.org/job/doc_ros2doc/
7. Merge PR to mark distribution as 'active' in rosdistro: https://github.com/ros/rosdistro/pull/33272
8. Merge PR to set release versions on the -release branch, like: https://github.com/ros2/ros2/pull/1274
9. Make tag on https://github.com/ros/rosdistro , like humble/2022-05-23
10. Do a sync by running the job https://build.ros2.org/job/Hrel_sync-packages-to-main/
11. Do a release on https://github.com/ros2/ros2/releases , uploading the binary artifacts and using language like from a previous release (https://github.com/ros2/ros2/releases/tag/release-humble-20220523).
12. Do the discourse post announcing the release, like https://discourse.ros.org/t/ros-2-humble-hawksbill-released/25729
13. Close out external issue tracking the release, like: https://github.com/ros2/ros2/issues/1149
14. Move all issues to Patch Release 1 board, and close out the project board related to this release, like https://github.com/orgs/ros2/projects/23

**Comment by marcoag** [comment]
🐢 🥳 🚀
